
import { Product, FragranceType } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Oud Silk Mood',
    brand: 'Maison Francis Kurkdjian',
    category: 'Unisex',
    type: FragranceType.EXTRAIT,
    price: 39500,
    description: 'An airy fragrance that weaves its way through your skin like a silk ribbon, blending Bulgarian rose with blue chamomile and oud.',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    notes: ['Bulgarian Rose', 'Blue Chamomile', 'Papyrus', 'Oud']
  },
  {
    id: 'p2',
    name: 'Baccarat Rouge 540',
    brand: 'Maison Francis Kurkdjian',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 42000,
    description: 'Luminous and sophisticated, Baccarat Rouge 540 lays on the skin like an amber, floral and woody breeze.',
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 5.0,
    notes: ['Jasmine', 'Saffron', 'Amberwood', 'Ambergris']
  },
  {
    id: 'p3',
    name: 'Lost Cherry',
    brand: 'Tom Ford',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 48500,
    description: 'A full-bodied journey into the once-forbidden; a contrasting scent that reveals a tempting dichotomy of playful, candy-like gleam.',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.7,
    notes: ['Black Cherry', 'Bitter Almond', 'Turkish Rose', 'Roasted Tonka Bean']
  },
  {
    id: 'p4',
    name: 'Aventus',
    brand: 'Creed',
    category: 'Men',
    type: FragranceType.EDP,
    price: 55000,
    description: 'Celebrating strength, power, and success, Aventus is the ultimate fragrance for the modern connoisseur.',
    image: 'https://images.unsplash.com/photo-1557170334-a9632e77c6e4?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    notes: ['Pineapple', 'Birch', 'Musk', 'Blackcurrant']
  },
  {
    id: 'p5',
    name: 'Delina Exclusif',
    brand: 'Parfums de Marly',
    category: 'Women',
    type: FragranceType.EDP,
    price: 38500,
    description: 'A beautiful expression of femininity, Delina is a floral explosion that is both sweet and sensual.',
    image: 'https://images.unsplash.com/photo-1594411861611-e63073748281?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    notes: ['Lychee', 'Turkish Rose', 'Vanilla', 'Incense']
  },
  {
    id: 'p6',
    name: 'Reflection Man',
    brand: 'Amouage',
    category: 'Men',
    type: FragranceType.EDP,
    price: 39500,
    description: 'Compelling, distinctive and unmistakably masculine, Reflection Man embodies the spirit of refinement.',
    image: 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: false,
    rating: 4.8,
    notes: ['Rosemary', 'Orris', 'Jasmine', 'Sandalwood']
  },
  {
    id: 'p7',
    name: 'Bal d\'Afrique',
    brand: 'Byredo',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 32000,
    description: 'A warm and romantic vetiver inspired by the infatuation with African culture, art, music and dance.',
    image: 'https://images.unsplash.com/photo-1605614154625-26e3bc7c6807?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    notes: ['African Marigold', 'Bergamot', 'Cyclamen', 'Vetiver']
  },
  {
    id: 'p8',
    name: 'The Tragedy of Lord George',
    brand: 'Penhaligon\'s',
    category: 'Men',
    type: FragranceType.EDP,
    price: 34500,
    description: 'Lord George is a wealthy and respected man, the archetypal patriarch embodying the noblest values of the aristocracy.',
    image: 'https://images.unsplash.com/photo-1557827803-097435f99147?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: false,
    rating: 4.6,
    notes: ['Brandy', 'Shaving Soap', 'Tonka Bean']
  },
  {
    id: 'p9',
    name: 'Love, Don\'t Be Shy',
    brand: 'Kilian Paris',
    category: 'Women',
    type: FragranceType.EDP,
    price: 31500,
    description: 'An exhilarating fragrance that begs you to love. It is a sweet treat for adults.',
    image: 'https://images.unsplash.com/photo-1512203530485-2bc55d3fd71d?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.8,
    notes: ['Marshmallow', 'Orange Blossom', 'Honeysuckle']
  },
  {
    id: 'p10',
    name: 'Naxos',
    brand: 'Xerjoff',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 28500,
    description: 'Deep and sensual, Naxos is a tribute to the grandeur and glamour of the Mediterranean.',
    image: 'https://images.unsplash.com/photo-1615485244993-4981934ac2c5?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    notes: ['Honey', 'Tobacco', 'Lavender', 'Vanilla']
  },
  {
    id: 'p11',
    name: 'L\'Air du Desert Marocain',
    brand: 'Tauer Perfumes',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 24000,
    description: 'The scent of a desert night. Powerful, sensual and pure.',
    image: 'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: false,
    rating: 5.0,
    notes: ['Coriander', 'Cumin', 'Rock Rose', 'Cedarwood']
  },
  {
    id: 'p12',
    name: 'Layton',
    brand: 'Parfums de Marly',
    category: 'Men',
    type: FragranceType.EDP,
    price: 35500,
    description: 'A distinguished and addictive fragrance that perfectly fits the Parfums de Marly DNA.',
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.8,
    notes: ['Apple', 'Lavender', 'Vanilla', 'Cardamom']
  },
  {
    id: 'p13',
    name: 'Interlude Man',
    brand: 'Amouage',
    category: 'Men',
    type: FragranceType.EDP,
    price: 37500,
    description: 'An explosion of spices, Interlude Man is a fragrance of complexity and depth.',
    image: 'https://images.unsplash.com/photo-1588405864443-f11440aa3142?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: false,
    rating: 4.7,
    notes: ['Pimento Berry', 'Incense', 'Amber', 'Leather']
  },
  {
    id: 'p14',
    name: 'Mojave Ghost',
    brand: 'Byredo',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 32500,
    description: 'Inspired by the soulful beauty of the Mojave Desert, this woody composition is both light and complex.',
    image: 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    notes: ['Ambrette', 'Magnolia', 'Sandalwood', 'Cedarwood']
  },
  {
    id: 'p15',
    name: 'Philosykos',
    brand: 'Diptyque',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 26500,
    description: 'An ode to the entire fig tree: the green freshness of the leaves, the milky flavor of the figs.',
    image: 'https://images.unsplash.com/photo-1557170334-a9632e77c6e4?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    notes: ['Fig Leaf', 'Fig Sap', 'Fig Tree Wood', 'Black Pepper']
  },
  {
    id: 'p16',
    name: 'Portrait of a Lady',
    brand: 'Frederic Malle',
    category: 'Women',
    type: FragranceType.EDP,
    price: 46000,
    description: 'A baroque, sumptuous and symphonic perfume of character and classic elegance.',
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    notes: ['Rose', 'Clove', 'Raspberry', 'Patchouli']
  },
  {
    id: 'p17',
    name: 'Green Irish Tweed',
    brand: 'Creed',
    category: 'Men',
    type: FragranceType.EDP,
    price: 52000,
    description: 'A classic fougère fragrance, Green Irish Tweed is evocative of the lush greenery of the Emerald Isle.',
    image: 'https://images.unsplash.com/photo-1608528577224-192a54406114?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: false,
    rating: 4.7,
    notes: ['Lemon Verbena', 'Iris', 'Violet Leaf', 'Ambergris']
  },
  {
    id: 'p18',
    name: 'Gypsy Water',
    brand: 'Byredo',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 31000,
    description: 'A glamorization of the Romany lifestyle, based on a fascination for the myth.',
    image: 'https://images.unsplash.com/photo-1512203530485-2bc55d3fd71d?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.6,
    notes: ['Bergamot', 'Lemon', 'Incense', 'Pine Needle']
  },
  {
    id: 'p19',
    name: 'Soleil Blanc',
    brand: 'Tom Ford',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 44500,
    description: 'An addictive solar floral amber that unapologetically exudes the pursuit of sun and luxury.',
    image: 'https://images.unsplash.com/photo-1563170351-be82bc888bb4?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: false,
    rating: 4.5,
    notes: ['Pistachio', 'Bergamot', 'Tuberose', 'Coconut']
  },
  {
    id: 'p20',
    name: 'Black Orchid',
    brand: 'Tom Ford',
    category: 'Women',
    type: FragranceType.EDP,
    price: 28500,
    description: 'A luxurious and sensual fragrance of rich, dark accords and alluring spice.',
    image: 'https://images.unsplash.com/photo-1615485244993-4981934ac2c5?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    notes: ['French Jasmine', 'Black Truffle', 'Ylang-Ylang', 'Patchouli']
  },
  {
    id: 'p21',
    name: 'Santal 33',
    brand: 'Le Labo',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 36000,
    description: 'A cult classic, Santal 33 is a crackling fire under a smoky sky.',
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    notes: ['Cardamom', 'Iris', 'Violet', 'Sandalwood']
  },
  {
    id: 'p22',
    name: 'Oud for Greatness',
    brand: 'Initio Parfums Prives',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 48500,
    description: 'A magnetic fragrance that breathes the power of the soul, using the finest natural oud.',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.8,
    notes: ['Lavender', 'Saffron', 'Nutmeg', 'Oud']
  },
  {
    id: 'p23',
    name: 'Black Phantom',
    brand: 'Kilian Paris',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 36500,
    description: 'Memento Mori: A mysterious fragrance that blends coffee, rum, and sugar cane.',
    image: 'https://images.unsplash.com/photo-1512203530485-2bc55d3fd71d?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: false,
    rating: 4.7,
    notes: ['Rum', 'Coffee', 'Vetiver', 'Cyanide Accord']
  },
  {
    id: 'p24',
    name: 'Halfeti',
    brand: 'Penhaligon\'s',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 31000,
    description: 'A journey into the Orient, with dark roses and mysterious spices.',
    image: 'https://images.unsplash.com/photo-1557827803-097435f99147?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    notes: ['Saffron', 'Grapefruit', 'Rose', 'Oud']
  },
  {
    id: 'p25',
    name: 'Side Effect',
    brand: 'Initio Parfums Prives',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 41500,
    description: 'The thrill of the forbidden, Side Effect plays with tobacco, vanilla, and rum.',
    image: 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.9,
    notes: ['Tobacco', 'Vanilla', 'Rum', 'Cinnamon']
  },
  {
    id: 'p26',
    name: 'Another 13',
    brand: 'Le Labo',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 36000,
    description: 'An addictive, dirty-clean scent that blends ambroxan with jasmine and moss.',
    image: 'https://images.unsplash.com/photo-1594411861611-e63073748281?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.8,
    notes: ['Ambroxan', 'Jasmine', 'Moss', 'Ambrette']
  },
  {
    id: 'p27',
    name: 'Herod',
    brand: 'Parfums de Marly',
    category: 'Men',
    type: FragranceType.EDP,
    price: 38500,
    description: 'A sophisticated tobacco fragrance, Herod is a blend of spicy notes and sweet vanilla.',
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    notes: ['Cinnamon', 'Tobacco Leaf', 'Incense', 'Vanilla']
  },
  {
    id: 'p28',
    name: 'Hibiscus Mahajád',
    brand: 'Maison Crivelli',
    category: 'Unisex',
    type: FragranceType.EXTRAIT,
    price: 33500,
    description: 'A powerful floral extraction, blending hibiscus and rose with a hint of spicy vanilla.',
    image: 'https://images.unsplash.com/photo-1563170351-be82bc888bb4?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: false,
    rating: 4.7,
    notes: ['Hibiscus', 'Rose', 'Cinnamon', 'Vanilla']
  },
  {
    id: 'p29',
    name: 'Super Cedar',
    brand: 'Byredo',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 31000,
    description: 'A woody fragrance inspired by the crisp scent of cedar shavings, simple and profound.',
    image: 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: false,
    rating: 4.5,
    notes: ['Rose Petals', 'Virginian Cedar', 'Haitian Vetiver', 'Musk']
  },
  {
    id: 'p30',
    name: 'Silver Mountain Water',
    brand: 'Creed',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 52000,
    description: 'Evoking the sparkling streams of the Swiss Alps, this fragrance is crisp, clean, and icy.',
    image: 'https://images.unsplash.com/photo-1608528577224-192a54406114?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.6,
    notes: ['Bergamot', 'Green Tea', 'Blackcurrant', 'Sandalwood']
  },
  {
    id: 'p31',
    name: 'Erba Pura',
    brand: 'Xerjoff',
    category: 'Unisex',
    type: FragranceType.EDP,
    price: 31500,
    description: 'A delicious basket of Mediterranean fruits and citrus over an amber base.',
    image: 'https://images.unsplash.com/photo-1615485244993-4981934ac2c5?auto=format&fit=crop&q=80&w=600',
    isNew: true,
    isBestSeller: true,
    rating: 4.8,
    notes: ['Orange', 'Lemon', 'Bergamot', 'White Musk']
  },
  {
    id: 'p32',
    name: 'Jubilation XXV',
    brand: 'Amouage',
    category: 'Men',
    type: FragranceType.EDP,
    price: 41500,
    description: 'A fragrance created for the enigmatic man carrying the essence of his own philosophy across eras.',
    image: 'https://images.unsplash.com/photo-1588405864443-f11440aa3142?auto=format&fit=crop&q=80&w=600',
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    notes: ['Frankincense', 'Blackberry', 'Honey', 'Myrrh']
  }
];

export const REVIEWS = [
  {
    id: 1,
    name: 'Sofia Al-Fayed',
    rating: 5,
    text: "Frag Avenue is the only place in Dhaka I trust for my niche collection. The Oud Silk Mood arrived in pristine condition, gift-wrapped like a work of art.",
    location: 'Dhaka, BD'
  },
  {
    id: 2,
    name: 'Julian Vane',
    rating: 5,
    text: "The concierge service is truly top-tier. Baccarat Rouge 540 is my signature scent, and their authenticity is impeccable. A standard above the rest.",
    location: 'Paris, FR'
  },
  {
    id: 3,
    name: 'Zahra Hassan',
    rating: 5,
    text: "Extraordinary selection. I found scents here that aren't available anywhere else in the region. Their delivery was faster than expected.",
    location: 'Dubai, UAE'
  },
  {
    id: 4,
    name: 'Marcus Thorne',
    rating: 5,
    text: "Exquisite presentation and genuine products. The team really understands the soul of niche perfumery. My Aventus purchase was seamless.",
    location: 'London, UK'
  }
];
